const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const WATCHLIST = path.join(ROOT, 'watchlist.txt');
const OUT = path.join(ROOT, 'data.json');
const COMPANY = {SPY:'SPDR S&P 500 ETF Trust',TSLA:'Tesla, Inc.',NVDA:'NVIDIA Corporation',GM:'General Motors Company',MSFT:'Microsoft Corporation',GOOG:'Alphabet Inc.',AVGO:'Broadcom Inc.',IAU:'iShares Gold Trust',MU:'Micron Technology, Inc.',IBIT:'iShares Bitcoin Trust ETF',AMAT:'Applied Materials, Inc.',GLW:'Corning Incorporated',COHR:'Coherent Corp.',ORCL:'Oracle Corporation',SNDK:'SanDisk Corporation',AAPL:'Apple Inc.',AMD:'Advanced Micro Devices, Inc.',META:'Meta Platforms, Inc.',SOXL:'Direxion Daily Semiconductor Bull 3X Shares',INTC:'Intel Corporation',BE:'Bloom Energy Corporation',EWY:'iShares MSCI South Korea ETF',BRT:'BRT Apartments Corp.',AXTI:'AXT, Inc.',LITE:'Lumentum Holdings Inc.',AAOI:'Applied Optoelectronics, Inc.',AMZN:'Amazon.com, Inc.',JPM:'JPMorgan Chase & Co.',QQQ:'Invesco QQQ Trust',SOFI:'SoFi Technologies, Inc.',UUUU:'Energy Fuels Inc.'};
function readWatchlist(){return fs.readFileSync(WATCHLIST,'utf8').split(/\r?\n/).map(s=>s.trim().toUpperCase()).filter(s=>s&&!s.startsWith('#'))}
function ema(values, period){const k=2/(period+1);let prev=null;return values.map(v=>{prev=prev==null?v:v*k+prev*(1-k);return prev})}
function sma(values, period){return values.map((_,i)=>{const start=Math.max(0,i-period+1),seg=values.slice(start,i+1).filter(Number.isFinite);return seg.length?seg.reduce((a,b)=>a+b,0)/seg.length:null})}
function macd(c){const e12=ema(c,12),e26=ema(c,26),dif=c.map((_,i)=>e12[i]-e26[i]),dea=ema(dif,9),hist=dif.map((x,i)=>x-dea[i]);return{dif,dea,hist}}
function macdSignal(hist,dif,dea){let n=hist.length-1,h=hist[n],hp=hist[n-1],d=dif[n],a=dea[n],dp=dif[n-1],ap=dea[n-1];if(d>a&&dp<=ap)return{key:'buy',label:'买入',badge:'金叉'};if(d<a&&dp>=ap)return{key:'sell',label:'卖出',badge:'死叉'};if(d>a&&h>=0)return{key:'hold',label:'持有',badge:'多头'};if(d<a&&h<=0)return{key:'watch',label:'观望',badge:'空头'};if(h>hp)return{key:'watch',label:'观望',badge:'动能增强'};return{key:'watch',label:'观望',badge:'等待'}}
function emaSignal(e8,e21){const n=e8.length-1,fast=e8[n],slow=e21[n],pf=e8[n-1],ps=e21[n-1],spread=fast-slow,prevSpread=pf-ps;if(fast>slow&&pf<=ps)return{key:'buy',label:'买入',badge:'金叉'};if(fast<slow&&pf>=ps)return{key:'sell',label:'卖出',badge:'死叉'};if(fast>slow)return{key:'hold',label:'持有',badge:spread>=prevSpread?'多头增强':'多头'};if(fast<slow)return{key:'watch',label:'观望',badge:spread<=prevSpread?'空头增强':'空头'};return{key:'watch',label:'观望',badge:'等待'}}
function kdj(rows,period=9){const k=[],d=[],j=[];let pk=50,pd=50;for(let i=0;i<rows.length;i++){const start=Math.max(0,i-period+1),seg=rows.slice(start,i+1),hi=Math.max(...seg.map(r=>r.high)),lo=Math.min(...seg.map(r=>r.low)),c=rows[i].close;const rsv=hi===lo?50:(c-lo)/(hi-lo)*100;pk=pk*2/3+rsv/3;pd=pd*2/3+pk/3;k.push(pk);d.push(pd);j.push(3*pk-2*pd)}return{k,d,j}}
function kdjSignal(k,d){const n=k.length-1,kv=k[n],dv=d[n],pv=k[n-1],pd=d[n-1];if(kv>dv&&pv<=pd&&dv<20)return{key:'buy',label:'买入',badge:'D<20金叉'};if(kv<dv&&pv>=pd&&dv>80)return{key:'sell',label:'卖出',badge:'D>80死叉'};if(dv<20)return{key:'watch',label:'观望',badge:'超卖区'};if(dv>80)return{key:'watch',label:'观望',badge:'超买区'};if(kv>dv)return{key:'hold',label:'持有',badge:'K>D'};return{key:'watch',label:'观望',badge:'等待'}}
function maSignal(fast,slow){const n=fast.length-1,maF=fast[n],maS=slow[n],pF=fast[n-1],pS=slow[n-1],slowUp=maS>(slow[n-1]??maS),spread=maF-maS,prevSpread=pF-pS;if(maF>maS&&pF<=pS&&slowUp)return{key:'buy',label:'买入',badge:'价格金叉'};if(maF<maS&&pF>=pS)return{key:'sell',label:'卖出',badge:'价格死叉'};if(maF>maS)return{key:'hold',label:'持有',badge:spread>=prevSpread?'多头增强':'多头'};return{key:'watch',label:'观望',badge:'等待'}}
function volSignal(fast,slow,vol){const n=fast.length-1,mvF=fast[n],mvS=slow[n],pF=fast[n-1],pS=slow[n-1],strong=vol[n]>mvS*1.5,spread=mvF-mvS,prevSpread=pF-pS;if(mvF>mvS&&pF<=pS&&strong)return{key:'buy',label:'买入',badge:'量价金叉'};if(mvF<mvS&&pF>=pS)return{key:'sell',label:'卖出',badge:'量能死叉'};if(mvF>mvS)return{key:'hold',label:'持有',badge:strong?'放量多头':'量能多头'};return{key:'watch',label:'观望',badge:'等待'}}
function crossAge(fast,slow,rows){let n=fast.length-1;if(!(fast[n]>slow[n]))return{bullish:false,days:0,date:null,weakening:false,label:'未多头'};let idx=0;for(let i=n;i>=1;i--)if(fast[i]>slow[i]&&fast[i-1]<=slow[i-1]){idx=i;break}const spread=fast.map((x,i)=>x-slow[i]),start=Math.max(idx,n-9),seg=spread.slice(start,n+1),cur=spread[n],prev=spread[n-1]??cur,prev2=spread[n-2]??prev,peak=Math.max(...seg);const falling3=cur<prev&&prev<prev2;const fromPeak=peak>0?(peak-cur)/peak:0;const weakening=!!(cur>0&&(falling3||fromPeak>=0.45));const label=weakening?'明显走弱':(cur>prev?'动能增强':'正常回落');return{bullish:true,days:n-idx+1,date:rows[idx].date,weakening,label,spreadPeak:+peak.toFixed(4),spreadChange:+(cur-prev).toFixed(4),dropFromPeak:+(fromPeak*100).toFixed(1)}}
function kdjCrossAge(k,d,rows){let n=k.length-1;if(!(k[n]>d[n]))return{bullish:false,days:0,date:null,weakening:false,label:'未金叉'};let idx=0;for(let i=n;i>=1;i--)if(k[i]>d[i]&&k[i-1]<=d[i-1]){idx=i;break}const curD=d[n],prevD=d[n-1]??curD,prev2D=d[n-2]??prevD;const weakening=curD>80&&curD<prevD&&prevD<prev2D;const label=curD<20?'超卖金叉区':curD>80?(weakening?'高位钝化走弱':'高位钝化'):(curD>prevD?'动能回升':'正常回落');return{bullish:true,days:n-idx+1,date:rows[idx].date,weakening,label,d:+curD.toFixed(2),k:+k[n].toFixed(2)}}
function summarizeViews(symbol,name,date,price,views,beta){const defs=[['macd','MACD'],['ema','EMA8/21'],['kdj','KDJ'],['priceCross','价格'],['volumeCross','量价']];const crosses=defs.map(([key,label])=>({key,label,signal:views[key].signal,badge:views[key].signal.badge}));const buys=crosses.filter(x=>x.signal.key==='buy'),sells=crosses.filter(x=>x.signal.key==='sell'),holds=crosses.filter(x=>x.signal.key==='hold');const key=buys.length?'buy':sells.length?'sell':holds.length?'hold':'watch';const badge=buys.length?`${buys.length}个金叉`:sells.length?`${sells.length}个死叉`:holds.length?`${holds.length}个偏多`:'无交叉';const r={symbol,name,date,price,signal:{key,label:key==='buy'?'买入':key==='sell'?'卖出':key==='hold'?'持有':'观望',badge},crosses,buys,sells,holds,updatedAt:new Date().toISOString()};if(Number.isFinite(beta))r.beta=beta;return r}
async function fetchBeta(symbol){const ySymbol=symbol.replace('.','-');const url=`https://query2.finance.yahoo.com/v10/finance/quoteSummary/${encodeURIComponent(ySymbol)}?modules=defaultKeyStatistics`;try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)return NaN;const j=await r.json();const b=j?.quoteSummary?.result?.[0]?.defaultKeyStatistics?.beta?.raw;return Number.isFinite(b)?+b.toFixed(3):NaN}catch{return NaN}}
async function fetchSym(s){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?range=6mo&interval=1d&includePrePost=false&events=div%2Csplits`;const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`Yahoo ${r.status}`);const j=await r.json();const x=j.chart?.result?.[0];if(!x)throw new Error('no chart data');const q=x.indicators.quote[0];const rows=x.timestamp.map((t,i)=>({date:new Date(t*1000).toISOString().slice(0,10),high:q.high[i],low:q.low[i],close:q.close[i],volume:q.volume[i]})).filter(r=>Number.isFinite(r.close)&&Number.isFinite(r.high)&&Number.isFinite(r.low)&&Number.isFinite(r.volume));if(rows.length<35)throw new Error('not enough data');const c=rows.map(r=>r.close),v=rows.map(r=>r.volume),m=macd(c),e8=ema(c,8),e21=ema(c,21),kd=kdj(rows),ma8=sma(c,8),ma21=sma(c,21),mv5=sma(v,5),mv20=sma(v,20),n=rows.length-1;const beta=await fetchBeta(s);const views={macd:{signal:macdSignal(m.hist,m.dif,m.dea),dif:m.dif[n],dea:m.dea[n],hist:m.hist[n],crossAge:crossAge(m.dif,m.dea,rows),histTail:m.hist.slice(-28).map(x=>+x.toFixed(4))},ema:{signal:emaSignal(e8,e21),ema8:e8[n],ema21:e21[n],spread:e8[n]-e21[n],crossAge:crossAge(e8,e21,rows),spreadTail:e8.slice(-28).map((x,i)=>+(x-e21[e21.length-28+i]).toFixed(4))},kdj:{signal:kdjSignal(kd.k,kd.d),k:kd.k[n],d:kd.d[n],j:kd.j[n],crossAge:kdjCrossAge(kd.k,kd.d,rows),kdjTail:kd.k.slice(-28).map((x,i)=>+(x-kd.d[kd.d.length-28+i]).toFixed(4))},priceCross:{signal:maSignal(ma8,ma21),maFast:ma8[n],maSlow:ma21[n],spread:ma8[n]-ma21[n],crossAge:crossAge(ma8,ma21,rows),maTail:ma8.slice(-28).map((x,i)=>+(x-ma21[ma21.length-28+i]).toFixed(4))},volumeCross:{signal:volSignal(mv5,mv20,v),mavolFast:mv5[n],mavolSlow:mv20[n],volume:v[n],volumeRatio:v[n]/mv20[n],spread:mv5[n]-mv20[n],crossAge:crossAge(mv5,mv20,rows),volTail:mv5.slice(-28).map((x,i)=>+(x-mv20[mv20.length-28+i]).toFixed(0))}};return{symbol:s,name:COMPANY[s]||s,date:rows[n].date,price:rows[n].close,beta,...views,summary:summarizeViews(s,COMPANY[s]||s,rows[n].date,rows[n].close,views,beta),updatedAt:new Date().toISOString()}}
function viewOf(item,kind){if(item.error)return item;const r={symbol:item.symbol,name:item.name,date:item.date,price:item.price,...item[kind],updatedAt:item.updatedAt};if(item.beta!=null)r.beta=item.beta;return r}
function sortItems(items){const order={buy:0,hold:1,watch:2,sell:3};return items.sort((a,b)=>(order[a.signal?.key]??9)-(order[b.signal?.key]??9)||(b.crossAge?.days||0)-(a.crossAge?.days||0)||a.symbol.localeCompare(b.symbol))}
function sortSummary(items){const score=x=>(x.buys?.length||0)*10+(x.sells?.length||0)*6+(x.holds?.length||0);return items.sort((a,b)=>score(b)-score(a)||a.symbol.localeCompare(b.symbol))}
function counts(items){const out={buy:0,hold:0,sell:0,watch:0,total:items.length};for(const it of items)if(it.signal)out[it.signal.key]++;return out}

async function fetchMarketIndicators(){try{const vixR=await fetch("https://query1.finance.yahoo.com/v8/finance/chart/%5EVIX?range=10d&interval=1d",{headers:{"user-agent":"Mozilla/5.0"}});const vixJ=await vixR.json();const vixQ=vixJ.chart.result[0].indicators.quote[0];const vCloses=vixQ.close.filter(c=>c!=null);const vixNum=vCloses[vCloses.length-1];const vixPrev=vCloses[vCloses.length-2];const vix={value:+vixNum.toFixed(2),change:+((vixNum-vixPrev)).toFixed(2),changePct:+((vixNum/vixPrev-1)*100).toFixed(2)};let fg=null;try{const fgR=await fetch("https://production.dataviz.cnn.io/index/fearandgreed/graphdata",{headers:{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36","Accept":"application/json","Origin":"https://www.cnn.com","Referer":"https://www.cnn.com/"}});const fgJ=await fgR.json();const f=fgJ.fear_and_greed;fg={score:Math.round(f.score),rating:f.rating}}catch(e){}return{vix,fg}}catch(e){return{vix:null,fg:null}}}

(async()=>{const symbols=readWatchlist();const settled=await Promise.allSettled(symbols.map(fetchSym));const raw=settled.map((r,i)=>r.status==="fulfilled"?r.value:{symbol:symbols[i],error:r.reason.message});const macdItems=sortItems(raw.map(x=>viewOf(x,"macd")));const emaItems=sortItems(raw.map(x=>viewOf(x,"ema")));const kdjItems=sortItems(raw.map(x=>viewOf(x,"kdj")));const priceItems=sortItems(raw.map(x=>viewOf(x,"priceCross")));const volumeItems=sortItems(raw.map(x=>viewOf(x,"volumeCross")));const summaryItems=sortSummary(raw.map(x=>viewOf(x,"summary")));const indicators=await fetchMarketIndicators();const payload={generatedAt:new Date().toISOString(),watchlist:symbols,counts:counts(macdItems),items:macdItems,views:{macd:{counts:counts(macdItems),items:macdItems},ema:{counts:counts(emaItems),items:emaItems},kdj:{counts:counts(kdjItems),items:kdjItems},priceCross:{counts:counts(priceItems),items:priceItems},volumeCross:{counts:counts(volumeItems),items:volumeItems},summary:{counts:counts(summaryItems),items:summaryItems}},marketIndicators:indicators,source:"GitHub Action generated from Yahoo Finance"};fs.writeFileSync(OUT, JSON.stringify(payload,null,2)+"\n");console.log("wrote " + OUT + " with " + symbols.length + " items");})();
