const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const WATCHLIST = path.join(ROOT, 'watchlist.txt');
const OUT = path.join(ROOT, 'data.json');
const COMPANY = {SPY:'SPDR S&P 500 ETF Trust',TSLA:'Tesla, Inc.',NVDA:'NVIDIA Corporation',GM:'General Motors Company',MSFT:'Microsoft Corporation',GOOG:'Alphabet Inc.',AVGO:'Broadcom Inc.',IAU:'iShares Gold Trust',MU:'Micron Technology, Inc.',IBIT:'iShares Bitcoin Trust ETF',AMAT:'Applied Materials, Inc.',GLW:'Corning Incorporated',COHR:'Coherent Corp.',ORCL:'Oracle Corporation',SNDK:'SanDisk Corporation',AAPL:'Apple Inc.',AMD:'Advanced Micro Devices, Inc.',META:'Meta Platforms, Inc.',SOXL:'Direxion Daily Semiconductor Bull 3X Shares',INTC:'Intel Corporation',BE:'Bloom Energy Corporation',EWY:'iShares MSCI South Korea ETF',BRT:'BRT Apartments Corp.',AXTI:'AXT, Inc.',LITE:'Lumentum Holdings Inc.',AAOI:'Applied Optoelectronics, Inc.',AMZN:'Amazon.com, Inc.',JPM:'JPMorgan Chase & Co.',QQQ:'Invesco QQQ Trust',SOFI:'SoFi Technologies, Inc.',UUUU:'Energy Fuels Inc.'};
function readWatchlist(){return fs.readFileSync(WATCHLIST,'utf8').split(/\r?\n/).map(s=>s.trim().toUpperCase()).filter(s=>s&&!s.startsWith('#'))}
function ema(values, period){const k=2/(period+1);let prev=null;return values.map(v=>{prev=prev==null?v:v*k+prev*(1-k);return prev})}
function macd(c){const e12=ema(c,12),e26=ema(c,26),dif=c.map((_,i)=>e12[i]-e26[i]),dea=ema(dif,9),hist=dif.map((x,i)=>x-dea[i]);return{dif,dea,hist}}
function macdSignal(hist,dif,dea){let n=hist.length-1,h=hist[n],hp=hist[n-1],d=dif[n],a=dea[n],dp=dif[n-1],ap=dea[n-1];if(d>a&&dp<=ap)return{key:'buy',label:'买入',badge:'金叉'};if(d<a&&dp>=ap)return{key:'sell',label:'卖出',badge:'死叉'};if(d>a&&h>=0)return{key:'hold',label:'持有',badge:'多头'};if(d<a&&h<=0)return{key:'watch',label:'观望',badge:'空头'};if(h>hp)return{key:'watch',label:'观望',badge:'动能增强'};return{key:'watch',label:'观望',badge:'等待'}}
function emaSignal(e8,e21){const n=e8.length-1,fast=e8[n],slow=e21[n],pf=e8[n-1],ps=e21[n-1],spread=fast-slow,prevSpread=pf-ps;if(fast>slow&&pf<=ps)return{key:'buy',label:'买入',badge:'金叉'};if(fast<slow&&pf>=ps)return{key:'sell',label:'卖出',badge:'死叉'};if(fast>slow)return{key:'hold',label:'持有',badge:spread>=prevSpread?'多头增强':'多头'};if(fast<slow)return{key:'watch',label:'观望',badge:spread<=prevSpread?'空头增强':'空头'};return{key:'watch',label:'观望',badge:'等待'}}
function crossAge(fast,slow,rows){let n=fast.length-1;if(!(fast[n]>slow[n]))return{bullish:false,days:0,date:null,weakening:false,label:'未多头'};let idx=0;for(let i=n;i>=1;i--)if(fast[i]>slow[i]&&fast[i-1]<=slow[i-1]){idx=i;break}const spread=fast.map((x,i)=>x-slow[i]),start=Math.max(idx,n-9),seg=spread.slice(start,n+1),cur=spread[n],prev=spread[n-1]??cur,prev2=spread[n-2]??prev,peak=Math.max(...seg);const falling3=cur<prev&&prev<prev2;const fromPeak=peak>0?(peak-cur)/peak:0;const weakening=!!(cur>0&&(falling3||fromPeak>=0.45));const label=weakening?'明显走弱':(cur>prev?'动能增强':'正常回落');return{bullish:true,days:n-idx+1,date:rows[idx].date,weakening,label,spreadPeak:+peak.toFixed(4),spreadChange:+(cur-prev).toFixed(4),dropFromPeak:+(fromPeak*100).toFixed(1)}}
async function fetchSym(s){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?range=6mo&interval=1d&includePrePost=false&events=div%2Csplits`;const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`Yahoo ${r.status}`);const j=await r.json();const x=j.chart?.result?.[0];if(!x)throw new Error('no chart data');const q=x.indicators.quote[0];const rows=x.timestamp.map((t,i)=>({date:new Date(t*1000).toISOString().slice(0,10),close:q.close[i]})).filter(r=>Number.isFinite(r.close));if(rows.length<35)throw new Error('not enough data');const c=rows.map(r=>r.close),m=macd(c),e8=ema(c,8),e21=ema(c,21),n=rows.length-1;return{symbol:s,name:COMPANY[s]||s,date:rows[n].date,price:rows[n].close,macd:{signal:macdSignal(m.hist,m.dif,m.dea),dif:m.dif[n],dea:m.dea[n],hist:m.hist[n],crossAge:crossAge(m.dif,m.dea,rows),histTail:m.hist.slice(-28).map(x=>+x.toFixed(4))},ema:{signal:emaSignal(e8,e21),ema8:e8[n],ema21:e21[n],spread:e8[n]-e21[n],crossAge:crossAge(e8,e21,rows),spreadTail:e8.slice(-28).map((x,i)=>+(x-e21[e21.length-28+i]).toFixed(4))},updatedAt:new Date().toISOString()}}
function viewOf(item,kind){if(item.error)return item;return{symbol:item.symbol,name:item.name,date:item.date,price:item.price,...item[kind],updatedAt:item.updatedAt}}
function sortItems(items){const order={buy:0,hold:1,watch:2,sell:3};return items.sort((a,b)=>(order[a.signal?.key]??9)-(order[b.signal?.key]??9)||(b.crossAge?.days||0)-(a.crossAge?.days||0)||a.symbol.localeCompare(b.symbol))}
function counts(items){const out={buy:0,hold:0,sell:0,watch:0,total:items.length};for(const it of items)if(it.signal)out[it.signal.key]++;return out}
(async()=>{const symbols=readWatchlist();const settled=await Promise.allSettled(symbols.map(fetchSym));const raw=settled.map((r,i)=>r.status==='fulfilled'?r.value:{symbol:symbols[i],error:r.reason.message});const macdItems=sortItems(raw.map(x=>viewOf(x,'macd')));const emaItems=sortItems(raw.map(x=>viewOf(x,'ema')));const payload={generatedAt:new Date().toISOString(),watchlist:symbols,counts:counts(macdItems),items:macdItems,views:{macd:{counts:counts(macdItems),items:macdItems},ema:{counts:counts(emaItems),items:emaItems}},source:'GitHub Action generated from Yahoo Finance'};fs.writeFileSync(OUT, JSON.stringify(payload,null,2)+'\n');console.log(`wrote ${OUT} with ${symbols.length} items for MACD and EMA`);})();
